name: Build and Publish python package

on:
  push:
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        description: 'The PyPI token'
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Generate lines list
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        python export.py
    - name: Build package
      run: |
        python -m pip install --upgrade build twine
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
