name: Build and Publish python package

on:
  create:
    tags:
      - '*'
  workflow_call:
    secrets:
      PYPI_API_TOKEN:
        description: 'The PyPI token'
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Set version
      run: |
        VERSION_NAME=$(echo ${{github.ref_name}} | sed -r 's/(v)([0-9]+.[0-9]+.[0-9]+)/\2/')
        sed -i "s/version='0.0.0'/version='$VERSION_NAME'/" ./setup.py

    - name: Generate lines list
      run: |
        python -m pip install --upgrade pip
        pip install requests
        python export.py

    - name: Build package
      run: |
        python -m pip install --upgrade build twine
        python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
